if((${CMAKE_MAJOR_VERSION} GREATER 3) OR ((${CMAKE_MAJOR_VERSION} EQUAL 3) AND (${CMAKE_MINOR_VERSION} GREATER 0)))
	# available since cmake 3.1
	set(CMAKE_CXX_STANDARD 14)
	set(CMAKE_CXX_STANDARD_REQUIRED ON)
else()
	set(CMAKE_CXX14_FLAGS -std=c++14 CACHE STRING "flags to enable C++14")
	set_property(CACHE CMAKE_CXX14_FLAGS PROPERTY ADVANCED TRUE)

	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_CXX14_FLAGS}")

	mark_as_advanced(FORCE CMAKE_CXX14_FLAGS)
endif()

# add_definitions(-D_GLIBCXX_USE_CXX11_ABI=1)
